import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"
opacity = 0.8
blur = true

dimensions.columns = 175
dimensions.lines = 45

option_as_alt = "Both"

[font]
normal.family = "JetbrainsMono Nerd Font"
size = 12

[scrolling]
history = 100000
multiplier = 4
