import = [
	# "~/.config/alacritty/themes/themes/tokyo-night.toml"
	"~/.config/alacritty/themes/themes/catppuccin_mocha.toml",
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Full"
opacity = 0.8
blur = true

dimensions.columns = 175
dimensions.lines = 45

option_as_alt = "Both"

[font]
normal.family = "JetbrainsMono Nerd Font"
# normal.family = "MesloLGL Nerd Font Mono"
size = 12

[scrolling]
history = 100000
multiplier = 4

[cursor]
style.blinking = "Always"
