" 显示行号
set number
" 显示标尺
set ruler
" 历史记录
set history=1000
" 显示输入命令
set showcmd
" 状态行显示的内容
set statusline=&F%m%r%h%w\ [FORMAT=%{$ff}]\ [TYPE=%Y]\ [POS=%l,%v][%p%%]\ %{strftime(\"%d/%m/%y\ -\ %H:%M\")}
" 启动显示状态行
set laststatus=2
" 语法高亮
syntax on
set fileencoding=utf-8
set termencoding=utf-8
set fileformat=unix
set encoding=utf-8
" 自动对齐
set autoindent
set smartindent
" 去掉vi一致性的模式，解决backspace的问题
set nocompatible
set backspace=indent,eol,start
set backspace=2
" tab
set tabstop=4
set softtabstop=4
" 禁用自动备份
set nobackup
set nowritebackup
set noswapfile
" 共享剪贴板
set clipboard+=unnamed
